sudo: false
language: ruby
rvm:
  - 2.4.1
  - jruby-9.2.7.0
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  gem: easy-crypto
  gemspec: easy-crypto.gemspec
  skip_cleanup: true
  on:
    tags: true
