sudo: false
language: ruby
rvm:
- 2.4.1
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  api_key:
    secure: im+Pd+6YWK7/xuPdje4NZWVXfbO9cbjrEfDVAzO7rXb4gsOCg5uZLNgdoLvm+h2RiYH90fdDD3GTHChSDFyHjlq4eXyoZTNgAIGkcCuLb3jKdUKjBwS6QpMniD1AwJSQLMQl/E8deCwjkrkOC91PORidpPbVo/M56tRPTSn5MshMX23Z6B6gaaegZTyANaTed91UV8Pkl6p7aPz8QW24fPWHPx6fVktlXM04cTlHH0WloafHAFYAdC5nuolHBD9XcTGvajj7558a/oJR6SjMlU+zKhzjlOFSlXSm6XHImTRSIQ1PnSFRAW1att5Aa8drtm/gvgN9srosiedKryjzsL0bl/gTjlVIv0i6gpF5/pnfxGN+n16GwSkBLctUUFz1aDQ1NDk7+Ob+HmB8OaoUsAfSCZ/GKgbjrjuP4dZIWmpTbjPiWqir2vid6qm+RSDm2vZ4GpatXfbuSWh1t9bKSVQSKsT0b5FMrowI4d69wvUFSECbZK0RvASiG/q9/GSj5cc9jboqAD3koKxvsqusoKBdOcPWYW1t9BFSKrGwmRrHQvUXUxqj+UwHQK6QMeYgOIAbhDCVTVSlLbrRxzX11f3GbMiU8ztQDb2CM+kI/IB2cxG1GtMnwYVxDTAV0Mnt2AvmBG3JFzg6mVE6JkExnN7uq9NE3aIVwGPillYUqI8=
